### ISSUE TITLE
assignment of search Filter Function

### ISSUE THREAD

**Issue by markhayton** [spongessuck/gm.typeaheadDropdown#3]
Is it possible to assign a search filter function to change the way it searches? For instance starts with instead of contains? I tried the normal
filter:search:searchFunction
And place a function in both the directive code and the parent scope but nothing was called.

Thanks

**Comment by spongessuck** [comment]
Sure, you just have to change the template. Right now it's piping `$viewValue` into the `filter` filter, which will match if the model string is contained in any property. You just need to replace this with your own custom filter.

```
... | filter: ctrl.myFilter | ...
```

Controller:

```
this.myFilter = function() {
    return function(item) {
        return item.myProperty.indexOf(model) == 0;
    }
}
```

**Comment by markhayton** [comment]
I've tried:
Putting this filter in your Demos "DemoCtrl" and using | filter: DemoCtrl.myFilter |
Putting this filter in the controller inside of the gm.typeaheadDropdown and not knowing what do put in | filter: ???? |
And just as a last resort just putting in | filter: ctrl.myFilter | with the filter in both of the previous locations and it never calls the filter .. or at least doesn't hit my break point on the filter.
It does break the original demo and the auto select when typing doesn't work any more.
Still confused as to how to make this work with your demo specifically.. 

Thanks for the quick response from the earlier question..

**Comment by markhayton** [comment]
I was able to get it to fire in the debugger and the search works with startWith now, although the matching entry in the list is not highlighted as in the original demo, so the Letters of the list label changes correctly, but the blue highlight doesnt track the matching entry. Close..

**Comment by markhayton** [comment]
I put the filter in 
gm.typeaheadDropdown Controller area like this.. 
$scope.myFilter = function () {
                return function (item) {
                    return item.name.indexOf(model) == 0;
                }
            };

Then called it from the template with | filter:myFilter |

It fires, but with not hightlighting in the list.. just wanted to be clear.. Thanks

**Comment by spongessuck** [comment]
Yes, I realized that because the directive has isolate scope, you'd need to change the directive's controller.

It really should be something passed in, I think, but for now check out this plunk:

http://plnkr.co/edit/6ErzgF?p=preview

You could also consider using the `ui-select` directive instead of this one. It does kind of the same thing and is more robust, although it could be overkill if you want something simple.

**Comment by markhayton** [comment]
I had to change the template to "| filter:myFilter |"
to get the plnkr to work, but yes, it matches the text correct, but doesn't hightlight the right matching list entry.
And yes, I wanted something super small. I have looked at some of the "KitchenSinkWare" solutions but its just to bloated with excess functionality.

**Comment by spongessuck** [comment]
Sorry, I should have explained- I put a new property on the items in the first dropdown called `location`. Check `script.js` for the details. It's not highlighting the text because the text doesn't contain the search term, but it should narrow down the matches. For instance, start typing in 'London' and Mary will get selected since that's her location.

**Comment by markhayton** [comment]
OK, I will check it out, thanks!
